### PR TITLE
fix: replace pkg_resources with stdlib

### PR DESCRIPTION
**Pull request by branchv**
No need to depend on setuptools just to get the version, we can use [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html#overview)

### CODE REVIEW

**Comment by skorokithakis** [comment]
Excellent, thank you, I knew this shouldn't have been necessary but didn't remember about `metadata`.

**Review by skorokithakis — APPROVED** [review]

**Comment by chenrui333** [comment]
@skorokithakis any chance cutting a new release per this PR merge? Thanks!

**Comment by skorokithakis** [comment]
Released 0.2.2, sorry!

**Comment by chenrui333** [comment]
Thanks!! 🙏

**Pull request merged**
